server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customers
    username: root
    password: 1234
    driverClassName: org.postgresql.Driver